services:
  sinfonietta:
    image: sinfonietta
    platform: linux/amd64
    pull_policy: build
    build:
      dockerfile: Dockerfile
    environment:
      RETHINKDB_CONNECTION_HOST: rethinkdb
    ports:
      - 127.0.0.1:8080:8080/tcp
    depends_on:
      - rethinkdb

  rethinkdb:
    image: rethinkdb:2-bullseye-slim
    ports:
      - 127.0.0.1:8888:8080/tcp
      - 127.0.0.1:28015:28015/tcp
    volumes:
      - rethinkdb_data:/data
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
    restart: unless-stopped

volumes:
  rethinkdb_data:
