parser: 'vue-eslint-parser'
extends:
  - 'plugin:vue/vue3-recommended'
  - '../../.eslintrc.yml'
parserOptions:
  parser: '@typescript-eslint/parser'
  extraFileExtensions:
    - '.vue'
plugins:
  - import
  - '@typescript-eslint'
  - vue
rules:
  'vue/component-name-in-template-casing':
    - error
    - kebab-case
  'vue/html-indent':
    - error
    - 4
  'vue/max-attributes-per-line':
    - off
  'vue/no-lone-template':
    - off
  'vue/no-multiple-template-root':
    - off
  'vue/no-v-html':
    - off
  'vue/require-v-for-key':
    - off
